blank_issues_enabled: false
contact_links:
  - name: Pivity Moderative Help
    url: https://www.gmodstore.com/help/tickets/create/site
    about: Please create a ticket here if you need help with the Pivity platform
  - name: Pivity Community Help
    url: https://www.gmodstore.com/community
    about: For any other questions 